_format_version: "3.0"
_transform: true

routes:
  - name: r2r-lambda
    paths: ["/"]

plugins:
  - route: r2r-lambda
    name: aws-lambda
    config:
      aws_region: ap-northeast-1
      aws_key: DUMMY_KEY
      aws_secret: DUMMY_SECRET
      function_name: function
      host: r2r-lambda
      port: 8080
      disable_https: true
      is_proxy_integration: false
      awsgateway_compatible: true
      base64_encode_body: false
      invocation_type: Event
